### ISSUE TITLE
$WAKATIME_HOME/.wakatime.cfg not being loaded

### ISSUE THREAD

**Issue by kusold** [wakatime/jetbrains-wakatime#110]
I was happy to see that #96 was merged in, but I'm still having issues.

I have `WAKATIME_HOME` set, but whenever I launch IntelliJ, I'm still being prompted for my Wakatime API token.

I think that the config isn't being loaded from the `WAKATIME_HOME` directory:
https://github.com/wakatime/jetbrains-wakatime/blob/8696999d13137b09464108f1343ddc1d2a768350/src/com/wakatime/intellij/plugin/ConfigFile.java#L21-L22

**Comment by kusold** [comment]
@alanhamlett I still am being prompted for my Wakatime config. The lines I referenced should probably be doing something long the lines of:
```
private static File configFile = new File(Dependencies.getResourceLocation(), WakaTime.CONFIG);
```
instead of hard coding `user.home`.

**Comment by alanhamlett** [comment]
Thanks for clarifying... fixed in today's release v9.3.0 with 17d5aa3f399b209cca4eaa28f72631686ac2a5b8.

**Comment by SonodaKazuto** [comment]
Hi, it seems this problem had been solved but it still occurs on my computer. Does anyone also have this problem. I'm now using Intellij Idea EAP on latest Intel MacBook Pro.
